load("@tree-sitter-format//tools:rules.bzl", "tsf_cc_test")

tsf_cc_test(
    name = "if_statements",
    srcs = ["IfStatements.cpp"],
    deps = [
        "//tree-sitter-format:formatter",
        "//tree-sitter-format:bracket_existance_traverser",
    ]
)