load("@tree-sitter-format//tools:rules.bzl", "tsf_cc_library")

tsf_cc_library(
    name = "configuration",
    hdrs = ["Configuration.h"],
    srcs = ["Configuration.cpp"],
    deps = ["//tree-sitter-format/style"],

    visibility = ["//visibility:public"],
)