# load("@tree-sitter-format//tools:rules.bzl", "tsf_cc_test")

# tsf_cc_test(
#     name = "namespaces",
#     srcs = ["namespaces.cpp"],
#     deps = [
#         "//tree-sitter-format:formatter",
#         "//tree-sitter-format:indentation_traverser",
#     ]
# )