load("//tools:rules.bzl", "tsf_cc_library")

tsf_cc_library(
    name = "catch2_test_main",
    srcs = [
        "catch2_test_main.cpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@catch2",
    ],
)