load("@tree-sitter-format//tools:rules.bzl", "tsf_cc_library")

tsf_cc_library(
    name = "style",
    hdrs = ["Style.h"],
    srcs = ["Style.cpp"],
    deps = ["@yaml-cpp"],

    visibility = ["//visibility:public"],
)